### ISSUE TITLE
Problems with the login.

### ISSUE THREAD

**Issue by alin-rautoiu** [alin-rautoiu/mastodroid#21]
Seen users complain about logging in then being thrown back to login in screen. Not sure what that's about.

**Comment by Gargron** [comment]
Additionally: Now that Mastodon has two-factor authentication, the password-grant oauth login is even less functional, because there is no way to enter an OTP token and login fails without it when 2FA is enabled. I suggest implementing a web view asap! You can also simply open a browser on the phone. You can use redirect URLs with custom schemas, for example `yourAppID://callback` and register that in Android and that will open your app so you can read the query string you get.

**Comment by charlag** [comment]
@Gargron thanks! Yep, we totally should. Seems like WebView is the only viable option now.
