### ISSUE TITLE
Clicking on user icon in threadview will crash the app

### ISSUE THREAD

**Issue by EmiMidnight** [alin-rautoiu/mastodroid#36]
This is due to expandUser() always assuming that we're in MainActivity, so calling it from a thread will result in a failing cast from ThreadActivity to MainActivity.

**Comment by charlag** [comment]
Is there a reason why there's no `ProfileActivity` but there is a `ProfileFragment`? Should I make one, @alin-rautoiu ? This thing confuses me a bit because I am more used to "1 activity - many fragments". I just don't know how to open profile from the thread if I cannot replace the fragment (because there's none on the screen currently)

**Comment by EmiMidnight** [comment]
I must admit I don't fully understand the whole activity/fragment system, but wouldn't it make sense to display the threadview in the same way as the userview?

**Comment by charlag** [comment]
The hell with that, simple wrapper activity won't hurt anyone. I also think that we need to add app bar to the profile.
